spring:
  #cloud:
  #azure:
  #keyvault:
  #secret:
  #property-sources[0]:
  #name: novickportal-db-vault
  #credential:
  #managed-identity-enabled: true
  #client-id: fb30513e-f035-437e-9e00-ccb031796744 #This is the Novick-portal-id
  #endpoint: https://novickportal-db-vault.vault.azure.net/
  #property-source-enabled: true
  profiles:
    active: none
  application:
    name: novick-customers
  datasource:
    password: HeroDigital2024! #${datasource-password}
    username: root #${datasource-username}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novick?serverTimezone=UTC&useSSL=true&requireSSL=false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        boot:
          allow_jdbc_metadata_access: false
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: never
  jackson:
    default-property-inclusion: non_null
