spring:
  cloud:
    azure:
      keyvault:
        secret:
          credential:
            managed-identity-enabled: true
            client-id: fb30513e-f035-437e-9e00-ccb031796744
          property-sources[0]:
            profile:
              subscription-id: ad6acc79-29dc-48af-9575-526ab04ee95f
            endpoint: https://novickportal-db-vault.vault.azure.net/
          property-source-enabled: true
  profiles:
    active: dev
  application:
    name: novick-customers
  datasource:
    password: ${datasource-password}
    username: ${datasource-username}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        boot:
          allow_jdbc_metadata_access: false
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: never

